version: '2.1'

services:
  short-url-db:
    container_name: short_url_db
    build: ./db
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=wxx1512
    healthcheck:
      test: exit 0
  cache-db:
    container_name: cache-db
    build: ./cache
    ports:
      - 6379:6379
    healthcheck:
      test: exit 0

  short-url-service:
    container_name: short_url_service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - DATABASE_URL=mysql+pymysql://root:wxx1512@short-url-db:3306/short_url_generation
    depends_on:
      short-url-db:
        condition: service_healthy
      cache-db:
        condition: service_healthy
    links:
      - short-url-db
      - cache-db
